### ISSUE TITLE
Add/Edit README

### ISSUE THREAD

**Issue by nkinsaul** [nkinsaul/HealthDash#20]
The README is formatted well and at a minimum contains:
Overview of project and goals
Overview of technologies used, challenges, wins, and any other reflections
Screenshots/gifs of your app

Resources:
https://thejunkland.com/blog/how-to-write-good-readme.html
https://gist.github.com/akashnimare/7b065c12d9750578de8e705fb4771d2f#file-readme-md
https://meakaakka.medium.com/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

**Comment by quynhtlluu** [comment]
Thank you so much for the additional information, Natalie!

**Comment by derekgithub2** [comment]
Each group member sends Quynh thoughts to include in the Wins/Challenges via Slack
