### ISSUE TITLE
Add function to randomize user on pageLoad

### ISSUE THREAD

**Issue by ElBrewster** [nkinsaul/HealthDash#44]
Looking at Iteration 1, looks like we missed a piece of the dashboard:
"To develop this dashboard, you should randomly generate a user"
We could probably use the randomness logic from our mod 1 posters project to generate a random user in the Load function or the addUser function (assess where would be the best place to call a random user)

**Comment by nkinsaul** [comment]
- Got it working for everything except the water chart.  Troubleshooting this now before making a PR to merge in the new function
