### ISSUE TITLE
Data Model User.js method #6: User Story: Miles Walked

### ISSUE THREAD

**Issue by ElBrewster** [nkinsaul/HealthDash#80]
For a specific day (specified by a date), return the miles a user has walked based on their number of steps (use their strideLength to help calculate this).
This method needs Activity data, and needs strideLength data from User.js (user1.strideLength).

    `it("Should have a method to calculate the miles a user has walked", () => {
        //--> method6: is this only for a particular day, or also a week?
        //--> do we need a mile calculation?
        //--> #steps(from Activity) + strideLength(from User) to calculate
    });`

**Comment by derekgithub2** [comment]
Also writing the test for this issue
